# Generated by Django 5.1.1 on 2024-11-16 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0003_alter_event_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_color',
            field=models.CharField(choices=[('#f2002b', 'Red'), ('#F64021', 'Redorange'), ('#F98016', 'Orange'), ('#FCC00B', 'Orangeyellow'), ('#FFFF00', 'Yellow'), ('#00CC66', 'Green'), ('#496DDB', 'Blue'), ('#7209B7', 'Purple'), ('#A01A7D', 'Magenta')], default='#496DDB', max_length=15),
        ),
    ]
