# Generated by Django 5.1.1 on 2024-11-21 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0004_event_event_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_place',
            field=models.CharField(default='', max_length=200),
        ),
    ]
